### PR TITLE
Merge previous team's updates into "staging" branch

### PR DESCRIPTION
**Pull request by annieshinn**
App seems to function properly as per all tests conducted.

### CODE REVIEW

**Review by taoantaoan — APPROVED** [review]
Thanks for updating this. I’m really enjoying being on this project!

**Review by astaiglesia — APPROVED** [review]
Merge approved. Application appears to function as demonstrated by the previous team with exceptions for bugs noted.

**Review by bielchristo — APPROVED** [review]
approved

**Review by sharon-zhu — APPROVED** [review]
Previous team merge clean up approved.

**Pull request merged**
